// <auto-generated />
namespace aegis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201701270653296_awal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201701270653296_awal));
        
        string IMigrationMetadata.Id
        {
            get { return "201701281918525_201701270653296_awal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
